version: '3.8'
services:
  API:
    image: favourite-clothing-store
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/favourite-cloth-store
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=qwertyuiop
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: postgres:13.3-alpine
    ports:
      - "5432:5432"

    environment:
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=qwertyuiop
      - POSTGRES_DB=favourite-cloth-store
      - POSTGRES_HOST_AUTH_METHOD=trust